[build]
command = "npm run build"
publish = "build"

[[redirects]]
from = "/api/*"
to = "http://ec2-13-51-201-196.eu-north-1.compute.amazonaws.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/model/*"
to = "http://ec2-13-60-215-21.eu-north-1.compute.amazonaws.com/model/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
